# -*- coding: utf-8 -*-
from odoo import models, fields


class AccountMove(models.Model):
    _inherit = 'account.move'

    abra_vehicle_id = fields.Many2one(
        'fleet.vehicle',
        string='Vehicle',
        copy=False,
        help='Set automatically when this vendor bill was generated by the '
             'scheduled fleet service check. Used to find and cancel a '
             'still-pending bill when "Mark as Serviced" is clicked on the vehicle.',
    )
